# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Bryan Liu
# Description of the Site
description: Problem solver skilled in data, statistics, and machine learning techniques.
# URL of Image of the Site
site-image: /assets/images/BryanLiu_1920x1080.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/BryanLiu_1920x1080.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: bryan@datahandyperson.com
linkedin_username: liuchbryan
google_scholar_id: YIyDgy8AAAAJ 
github_username: liuchbryan
youtube_channel_id: UCdVvCsSFtYhgozs54UKyaKQ
facebook_username:
twitter_username:
instagram_username:
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username:

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Dr Bryan Liu
# URL for the Image of the Author
author-image: /assets/images/BryanLiu_profile_400x400.png
# About the Author, in Markdown
author-about: |-
  I am a data scientist. I help business teams solve their data problems and realise tangible value. Often, I do so by leading cross-functional teams to build data pipelines and statistics/machine learning models.    
      
  Over the years (mainly at [ASOS.com](https://www.asos.com)), I have built many customer models and produced sales and returns forecasts. I have also learnt how to translate between technical and business, academia and industry, and science and engineering.   
       
  In addition, I specialise in measuring the impact of business decisions via online experiments. My PhD [at Imperial and Oxford](https://statml.io/) focuses on the practical data and statistical challenges when one starts experimenting from scratch.    
      
  I am a member of the Royal Statistical Society and the [UK Global Talent / Tech Nation Visa Alumni Network](https://technation.io/global-talent-alumni/). I review academic and technical work for conferences such as [AdKDD](https://www.adkdd.org/). I also mentor high school students seeking a tech or data science career via the [Social Mobility Foundation](https://www.socialmobility.org.uk/mentoring).
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linkedin.com/in/liuchbryan

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
